baseURL: 'https://maelghrib.github.io/'
languageCode: 'en-us'
title: 'maelghrib'
theme: 'hugo_papermod'

params:
  author: "Mustafa A. Elghrib"
  hideFooter: true
  ShowCodeCopyButtons: true
  DateFormat: "02 Jan 2006"

  profileMode:
    enabled: true
    title: "Mustafa A. Elghrib"
    description: "Experienced Software Engineer with 2+ years of expertise in 
    Development, Cloud, and DevOps. Possesses excellent collaboration skills, 
    having worked with international teams, and has strong professional English 
    communication skills. Takes ownership of tasks and projects, with a flexible 
    approach to learning and applying new technologies."

  socialIcons:
    - name: github
      url: "https://github.com/maelghrib"
    - name: twitter
      url: "https://twitter.com/maelghrib"
    - name: linkedin
      url: "https://linkedin.com/in/maelghrib"

permalinks:
  blogs: 'blogs/:filename/'

menu:
  main:
    - name: "blogs"
      weight: 1
      url: "blogs/"

